FROM python:3.12-slim

WORKDIR /yarncv

COPY docker/requirements.txt /yarncv

RUN pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
RUN pip install -r /yarncv/requirements.txt

COPY . /yarncv

EXPOSE 8000

CMD ["uvicorn", "app.web.main:app", "--host", "0.0.0.0", "--port", "8000"]